# Generated by Django 6.0.4 on 2026-08-31 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, help_text='Auto-generated trade reference, e.g. OTEC-2026-0001.', max_length=20, unique=True)),
                ('commodity_category', models.CharField(choices=[('coal', 'Coal'), ('iron', 'Iron Ore')], db_index=True, max_length=16, verbose_name='commodity')),
                ('commodity_grade', models.CharField(choices=[('coal.hard_coking', 'Hard Coking Coal (HCC)'), ('coal.semi_soft', 'Semi-Soft Coking Coal (SSCC)'), ('coal.pci', 'Pulverised Coal Injection (PCI)'), ('coal.thermal_6000', 'Thermal Coal — 6000 kcal/kg NAR'), ('coal.thermal_5500', 'Thermal Coal — 5500 kcal/kg NAR'), ('coal.anthracite', 'Anthracite'), ('iron.fines_62', 'Iron Ore Fines — 62% Fe'), ('iron.fines_58', 'Iron Ore Fines — 58% Fe'), ('iron.lump_65', 'Iron Ore Lump — 65% Fe'), ('iron.pellets', 'Iron Ore Pellets'), ('iron.concentrate', 'Iron Ore Concentrate')], db_index=True, max_length=32, verbose_name='grade')),
                ('tonnage', models.FloatField(help_text='Metric tonnes.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_price', models.FloatField(help_text='USD per tonne the cargo is being sold for.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='sale price')),
                ('purchase_price', models.FloatField(help_text='USD per tonne the cargo is being bought for.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='purchase price')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('confirmed', 'Contract Confirmed'), ('awaiting_vessel', 'Awaiting Vessel'), ('loading', 'Loading'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=24)),
                ('counterparty', models.CharField(help_text='Buyer, mill or trading house this cargo is placed with.', max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'), models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx')],
            },
        ),
    ]
